<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        
    }

    function index()
    {
        // $current_user = $this->session->userdata('sessiondata');  
        // $this->load->model( 'User_model' );
        // $user = $this->User_model->get_t_user_id($current_user['username']);
        // $current_id = $user["id"];

        // $data['t_dashboard'] = $current_id;
        $data['_view'] = 'dashboard';
        $this->load->view('layouts/full',$data);
    }
}
