<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Domaine_techno extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Domaine_techno_model');
    } 

    /*
     * Listing of t_domaine_techno
     */
    function index()
    {
        $data['t_domaine_techno'] = $this->Domaine_techno_model->get_all_t_domaine_techno();
        
        $data['_view'] = 'domaine_techno/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new t_domaine_techno
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_domaine' => $this->input->post('id_domaine'),
				'id_techno' => $this->input->post('id_techno'),
            );
            
            $t_domaine_techno_id = $this->Domaine_techno_model->add_t_domaine_techno($params);
            redirect('domaine_techno/index');
        }
        else
        {
			$this->load->model('Domaine_model');
			$data['all_t_domaine'] = $this->Domaine_model->get_all_t_domaine();

			$this->load->model('Techno_model');
			$data['all_t_techno'] = $this->Techno_model->get_all_t_techno();
            
            $data['_view'] = 'domaine_techno/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a t_domaine_techno
     */
    function edit($id)
    {   
        // check if the t_domaine_techno exists before trying to edit it
        $data['t_domaine_techno'] = $this->Domaine_techno_model->get_t_domaine_techno($id);
        
        if(isset($data['t_domaine_techno']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_domaine' => $this->input->post('id_domaine'),
					'id_techno' => $this->input->post('id_techno'),
                );

                $this->Domaine_techno_model->update_t_domaine_techno($id,$params);            
                redirect('domaine_techno/index');
            }
            else
            {
				$this->load->model('Domaine_model');
				$data['all_t_domaine'] = $this->Domaine_model->get_all_t_domaine();

				$this->load->model('Techno_model');
				$data['all_t_techno'] = $this->Techno_model->get_all_t_techno();

                $data['_view'] = 'domaine_techno/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The t_domaine_techno you are trying to edit does not exist.');
    } 

    /*
     * Deleting t_domaine_techno
     */
    function remove($id)
    {
        $t_domaine_techno = $this->Domaine_techno_model->get_t_domaine_techno($id);

        // check if the t_domaine_techno exists before trying to delete it
        if(isset($t_domaine_techno['id']))
        {
            $this->Domaine_techno_model->delete_t_domaine_techno($id);
            redirect('domaine_techno/index');
        }
        else
            show_error('The t_domaine_techno you are trying to delete does not exist.');
    }
    
}
