<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Domaine_theme_ip extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Domaine_theme_ip_model');
    } 

    /*
     * Listing of t_domaine_theme_ip
     */
    function index()
    {
        $data['t_domaine_theme_ip'] = $this->Domaine_theme_ip_model->get_all_t_domaine_theme_ip();
        
        $data['_view'] = 'domaine_theme_ip/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new t_domaine_theme_ip
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_domaine' => $this->input->post('id_domaine'),
				'id_ip' => $this->input->post('id_ip'),
				'id_theme' => $this->input->post('id_theme'),
            );
            
            $t_domaine_theme_ip_id = $this->Domaine_theme_ip_model->add_t_domaine_theme_ip($params);
            redirect('domaine_theme_ip/index');
        }
        else
        {            
            $data['_view'] = 'domaine_theme_ip/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a t_domaine_theme_ip
     */
    function edit($id)
    {   
        // check if the t_domaine_theme_ip exists before trying to edit it
        $data['t_domaine_theme_ip'] = $this->Domaine_theme_ip_model->get_t_domaine_theme_ip($id);
        
        if(isset($data['t_domaine_theme_ip']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_domaine' => $this->input->post('id_domaine'),
					'id_ip' => $this->input->post('id_ip'),
					'id_theme' => $this->input->post('id_theme'),
                );

                $this->Domaine_theme_ip_model->update_t_domaine_theme_ip($id,$params);            
                redirect('domaine_theme_ip/index');
            }
            else
            {
                $data['_view'] = 'domaine_theme_ip/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The t_domaine_theme_ip you are trying to edit does not exist.');
    } 

    /*
     * Deleting t_domaine_theme_ip
     */
    function remove($id)
    {
        $t_domaine_theme_ip = $this->Domaine_theme_ip_model->get_t_domaine_theme_ip($id);

        // check if the t_domaine_theme_ip exists before trying to delete it
        if(isset($t_domaine_theme_ip['id']))
        {
            $this->Domaine_theme_ip_model->delete_t_domaine_theme_ip($id);
            redirect('domaine_theme_ip/index');
        }
        else
            show_error('The t_domaine_theme_ip you are trying to delete does not exist.');
    }
    
}
