<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Hebergement extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Hebergement_model');
    } 

    /*
     * Listing of t_hebergement
     */
    function index()
    {
        $data['t_hebergement'] = $this->Hebergement_model->get_all_t_hebergement();        

        $res = array();
        foreach($data['t_hebergement'] as $row) {
			$element = new stdClass();
            $element->id = $row['id'];
            $element->name =  $row['name'];
            $element->url =  $row['url'];
            $element->login =  $row['login'];
            $element->password =  $row['password'];     
           
            
            $this->load->model('Ip_model');
            $ip_data = $this->Ip_model->get_ip_id_hebergement($row['id']);
            
            $element->nb_ip = ($ip_data != null && count($ip_data) >0 ) ? count($ip_data) : 0;

            $this->load->model('Domaine_model');
            $domaine_data = $this->Domaine_model->get_by_id_hebergement($row['id']);
            $element->nb_site = ($domaine_data != null && count($domaine_data) >0 ) ? count($domaine_data) : 0;
		
            $res[] = $element;	
        }
        $data['nb_hebergement'] = ($data['t_hebergement'] != null && count($data['t_hebergement']) >0 ) ? count($data['t_hebergement']) : 0;
        $data['t_hebergement'] = $res;  
        $data['_view'] = 'hebergement/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new t_hebergement
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'password' => $this->input->post('password'),
				'name' => $this->input->post('name'),
				'url' => $this->input->post('url'),
				'login' => $this->input->post('login'),
            );
            if($this->Hebergement_model->get_t_hebergement_by_name($this->input->post('name')) == 0)  
            {
                $t_hebergement_id = $this->Hebergement_model->add_t_hebergement($params);
                redirect('hebergement');
            }
            else
            {     
                $data['error_nom'] = "Cet hébergement existe déjà !";         
                $data['_view'] = 'hebergement/add';
                $this->load->view('layouts/full',$data);
            }
        }
        else
        {            
            $data['_view'] = 'hebergement/add';
            $this->load->view('layouts/full',$data);
        }  
    }  

    /*
     * Editing a t_hebergement
     */
    function edit($id)
    {   
        // check if the t_hebergement exists before trying to edit it
        $data['t_hebergement'] = $this->Hebergement_model->get_t_hebergement($id);
        
        if(isset($data['t_hebergement']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'password' => $this->input->post('password'),
					'name' => $this->input->post('name'),
					'url' => $this->input->post('url'),
					'login' => $this->input->post('login'),
                );
                // if($this->Hebergement_model->get_t_hebergement_by_name($this->input->post('name') ) == 0 && $data['t_hebergement']['name'] != $this->input->post('name'))  
                // {
                    $this->Hebergement_model->update_t_hebergement($id,$params);            
                    redirect('hebergement');
                // }
                // else
                // {
                //     $data['error_nom'] = "Cet hébergement existe déjà !";  
                //     $data['_view'] = 'hebergement/edit';
                //     $this->load->view('layouts/main',$data);
                // }
            }
            else
            {
                $data['_view'] = 'hebergement/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The t_hebergement you are trying to edit does not exist.');
    } 

    /*
     * Deleting t_hebergement
     */
    function remove($id)
    {
        $t_hebergement = $this->Hebergement_model->get_t_hebergement($id);

        // check if the t_hebergement exists before trying to delete it
        if(isset($t_hebergement['id']))
        {
            $this->Hebergement_model->delete_t_hebergement($id);
            redirect('hebergement');
        }
        else
            show_error('The t_hebergement you are trying to delete does not exist.');
    }

    function get_info_by_id(){
      
        if (isset($_GET['id'])) {           
           
            $hebergement =  $this->Hebergement_model->get_t_hebergement($_GET['id']);
          
            echo json_encode($hebergement);
            die;
           
        }
    }
    
}
