<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Hebergement extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Hebergement_model');
    } 

    /*
     * Listing of t_hebergement
     */
    function index()
    {
        $data['t_hebergement'] = $this->Hebergement_model->get_all_t_hebergement();
        
        $data['_view'] = 'hebergement/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new t_hebergement
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'password' => $this->input->post('password'),
				'name' => $this->input->post('name'),
				'url' => $this->input->post('url'),
				'login' => $this->input->post('login'),
            );
            
            $t_hebergement_id = $this->Hebergement_model->add_t_hebergement($params);
            redirect('hebergement/index');
        }
        else
        {            
            $data['_view'] = 'hebergement/add';
            $this->load->view('layouts/full',$data);
        }
    }  

    /*
     * Editing a t_hebergement
     */
    function edit($id)
    {   
        // check if the t_hebergement exists before trying to edit it
        $data['t_hebergement'] = $this->Hebergement_model->get_t_hebergement($id);
        
        if(isset($data['t_hebergement']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'password' => $this->input->post('password'),
					'name' => $this->input->post('name'),
					'url' => $this->input->post('url'),
					'login' => $this->input->post('login'),
                );

                $this->Hebergement_model->update_t_hebergement($id,$params);            
                redirect('hebergement/index');
            }
            else
            {
                $data['_view'] = 'hebergement/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The t_hebergement you are trying to edit does not exist.');
    } 

    /*
     * Deleting t_hebergement
     */
    function remove($id)
    {
        $t_hebergement = $this->Hebergement_model->get_t_hebergement($id);

        // check if the t_hebergement exists before trying to delete it
        if(isset($t_hebergement['id']))
        {
            $this->Hebergement_model->delete_t_hebergement($id);
            redirect('hebergement/index');
        }
        else
            show_error('The t_hebergement you are trying to delete does not exist.');
    }
    
}
