<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ip extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Ip_model');
    } 

    /*
     * Listing of t_ip
     */
    function index()
    {
        $data['t_ip'] = $this->Ip_model->get_all_t_ip();       

        $res = array();
        foreach($data['t_ip'] as $row) {
			$element = new stdClass();
            $element->id = $row['id'];
            $element->adresse =  $row['adresse'];
            $element->reverseip =  $row['reverseip'];     

            /**IP */               
            $this->load->model('Domaine_theme_ip_model');
            $domaine_ip = $this->Domaine_theme_ip_model->get_t_domaine_theme_ip_by_ip($row['id']);   
        
            $element->nb_site = ($domaine_ip != null && count($domaine_ip) >0 ) ? count($domaine_ip) : 0;
           
            $this->load->model('Hebergement_model');
			$hebergement = $this->Hebergement_model->get_t_hebergement($row['id_heberg']);
            $element->hebergement = $hebergement['name'];   
		
            $res[] = $element;	
        }

        $data['t_ip'] = $res;  
        $data['_view'] = 'ip/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new t_ip
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_heberg' => $this->input->post('id_heberg'),
                'adresse' => $this->input->post('adresse'),
                'reverseip' => $this->input->post('reverseip'),
            );
            
            $t_ip_id = $this->Ip_model->add_t_ip($params);
            redirect('ip/index');
        }
        else
        {
			$this->load->model('Hebergement_model');
			$data['all_t_hebergement'] = $this->Hebergement_model->get_all_t_hebergement();
            
            $data['_view'] = 'ip/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a t_ip
     */
    function edit($id)
    {   
        // check if the t_ip exists before trying to edit it
        $data['t_ip'] = $this->Ip_model->get_t_ip($id);
        
        if(isset($data['t_ip']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_heberg' => $this->input->post('id_heberg'),
                    'adresse' => $this->input->post('adresse'),
                    'reverseip' => $this->input->post('reverseip'),
                );

                $this->Ip_model->update_t_ip($id,$params);            
                redirect('ip/index');
            }
            else
            {
				$this->load->model('Hebergement_model');
				$data['all_t_hebergement'] = $this->Hebergement_model->get_all_t_hebergement();

                $data['_view'] = 'ip/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The t_ip you are trying to edit does not exist.');
    } 

    /*
     * Deleting t_ip
     */
    function remove($id)
    {
        $t_ip = $this->Ip_model->get_t_ip($id);

        // check if the t_ip exists before trying to delete it
        if(isset($t_ip['id']))
        {
            $this->Ip_model->delete_t_ip($id);
            redirect('ip/index');
        }
        else
            show_error('The t_ip you are trying to delete does not exist.');
    }

   
    
}
