<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Techno extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Techno_model');
    } 

    /*
     * Listing of t_techno
     */
    function index()
    {
        $data['t_techno'] = $this->Techno_model->get_all_t_techno();
        $data['nb_techno'] = ($data['t_techno'] != null && count($data['t_techno']) >0 ) ? count($data['t_techno']) : 0;
 
        $data['_view'] = 'techno/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new t_techno
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'name' => $this->input->post('name'),
            );
            
            $t_techno_id = $this->Techno_model->add_t_techno($params);
            redirect('techno');
        }
        else
        {            
            $data['_view'] = 'techno/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a t_techno
     */
    function edit($id)
    {   
        // check if the t_techno exists before trying to edit it
        $data['t_techno'] = $this->Techno_model->get_t_techno($id);
        
        if(isset($data['t_techno']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'name' => $this->input->post('name'),
                );

                $this->Techno_model->update_t_techno($id,$params);            
                redirect('techno');
            }
            else
            {
                $data['_view'] = 'techno/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The t_techno you are trying to edit does not exist.');
    } 

    /*
     * Deleting t_techno
     */
    function remove($id)
    {
        $t_techno = $this->Techno_model->get_t_techno($id);

        // check if the t_techno exists before trying to delete it
        if(isset($t_techno['id']))
        {
            $this->Techno_model->delete_t_techno($id);
            redirect('techno');
        }
        else
            show_error('The t_techno you are trying to delete does not exist.');
    }
    
}
