<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Theme extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Theme_model');
    } 

    /*
     * Listing of t_theme
     */
    function index()
    {
        $data['t_theme'] = $this->Theme_model->get_all_t_theme();
        
        $data['_view'] = 'theme/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new t_theme
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'name' => $this->input->post('name'),
            );
            
            $t_theme_id = $this->Theme_model->add_t_theme($params);
            redirect('theme/index');
        }
        else
        {            
            $data['_view'] = 'theme/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a t_theme
     */
    function edit($id)
    {   
        // check if the t_theme exists before trying to edit it
        $data['t_theme'] = $this->Theme_model->get_t_theme($id);
        
        if(isset($data['t_theme']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'name' => $this->input->post('name'),
                );

                $this->Theme_model->update_t_theme($id,$params);            
                redirect('theme/index');
            }
            else
            {
                $data['_view'] = 'theme/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The t_theme you are trying to edit does not exist.');
    } 

    /*
     * Deleting t_theme
     */
    function remove($id)
    {
        $t_theme = $this->Theme_model->get_t_theme($id);

        // check if the t_theme exists before trying to delete it
        if(isset($t_theme['id']))
        {
            $this->Theme_model->delete_t_theme($id);
            redirect('theme/index');
        }
        else
            show_error('The t_theme you are trying to delete does not exist.');
    }
    
}
