<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cms_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get t_cms by id
     */
    function get_t_cms($id)
    {
        return $this->db->get_where('t_cms',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all t_cms
     */
    function get_all_t_cms()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('t_cms')->result_array();
    }
        
    /*
     * function to add new t_cms
     */
    function add_t_cms($params)
    {
        $this->db->insert('t_cms',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update t_cms
     */
    function update_t_cms($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('t_cms',$params);
    }
    
    /*
     * function to delete t_cms
     */
    function delete_t_cms($id)
    {
        return $this->db->delete('t_cms',array('id'=>$id));
    }
}
