<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Domaine_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get t_domaine by id
     */
    function get_t_domaine($id)
    {
        return $this->db->get_where('t_domaine',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all t_domaine
     */
    function get_all_t_domaine()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('t_domaine')->result_array();
    }
        
    /*
     * function to add new t_domaine
     */
    function add_t_domaine($params)
    {
        $this->db->insert('t_domaine',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update t_domaine
     */
    function update_t_domaine($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('t_domaine',$params);
    }
    
    /*
     * function to delete t_domaine
     */
    function delete_t_domaine($id)
    {
        return $this->db->delete('t_domaine',array('id'=>$id));
    }

    /*
     * Get t_domaine by id_hebergement
     */
    function get_by_id_hebergement($id_hebergement)
    {
        $this->load->database();       

        $this->db->select( "*" );
        $this->db->from( 't_domaine' );
        $this->db->like( 'id_heberg', $id_hebergement );
        $this->db->order_by('id_heberg', 'asc');
        $query = $this->db->get();
        $domaine_data = $query->result();
        
        return $domaine_data;   
    }
}
