<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Domaine_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get t_domaine by id
     */
    function get_t_domaine($id)
    {
        return $this->db->get_where('t_domaine',array('id'=>$id))->row_array();
    }

        /*
     * Get t_domaine by name
     */
    function get_t_domaine_by_name($name)
    {
        return $this->db->get_where('t_domaine',array('nom'=>$name))->row_array();
    }
        
    /*
     * Get all t_domaine
     */
    function get_all_t_domaine()
    {
        $this->db->order_by('nom', 'asc');
        return $this->db->get('t_domaine')->result_array();
    }
        
    /*
     * function to add new t_domaine
     */
    function add_t_domaine($params)
    {
        $this->db->insert('t_domaine',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update t_domaine
     */
    function update_t_domaine($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('t_domaine',$params);
    }
    
    /*
     * function to delete t_domaine
     */
    function delete_t_domaine($id)
    {
        return $this->db->delete('t_domaine',array('id'=>$id));
    }

    /*
     * Get t_domaine by id_hebergement
     */
    function get_by_id_hebergement($id_hebergement)
    {
        $this->load->database();       

        $this->db->select( "*" );
        $this->db->from( 't_domaine' );
        $this->db->like( 'id_heberg', $id_hebergement );
        $this->db->order_by('id_heberg', 'asc');
        $query = $this->db->get();
        $domaine_data = $query->result_array();
        
        return $domaine_data;   
    }

    function get_by_id_registrar($id_registrar)
    {   
        $this->load->database();       

        $this->db->select( "*" );
        $this->db->from( 't_domaine' );
        $this->db->like( 'id_registrar', $id_registrar );
        $this->db->order_by('id_registrar', 'asc');
        $query = $this->db->get();
        $domaine_data = $query->result_array();
        
        return $domaine_data;   
    }

    function get_domaine_by_month(){

        // $this->load->database(); 
        // $this->db->select( "*" );
        // $this->db->from( 't_domaine' );
        // $this->db->order_by('date_creation','asc');
        // $this->db->query("GROUP BY MONTH('date_creation')");
        // $query = $this->db->get(); 
       
        $result = $this->db->select('DISTINCT DATE_FORMAT(`t`.`date_creation`, "%m") `mois`,COUNT(`t`.`id`) as nb', FALSE)->from('t_domaine `t`')->group_by('MONTH(`t`.`date_creation`)')->order_by('t.date_creation', 'ASC')->get()->result();
       
        $domaine_data = $result;   
       
        return $domaine_data;   
    }
}
