<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ip_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get t_ip by id
     */
    function get_t_ip($id)
    {
        return $this->db->get_where('t_ip',array('id'=>$id))->row_array();
    }
        
     /*
     * Get t_ip by id
     */
    function get_t_ip_by_adresse($adresse)
    {
        return $this->db->get_where('t_ip',array('adresse'=>$adresse))->row_array();
    }

    /*
     * Get all t_ip
     */
    function get_all_t_ip()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('t_ip')->result_array();
    }
        
    /*
     * function to add new t_ip
     */
    function add_t_ip($params)
    {
        $this->db->insert('t_ip',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update t_ip
     */
    function update_t_ip($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('t_ip',$params);
    }
    
    /*
     * function to delete t_ip
     */
    function delete_t_ip($id)
    {
        return $this->db->delete('t_ip',array('id'=>$id));
    }

     /*
     * Get t_ip by id_hebergement
     */
    function get_by_id_hebergement($id_hebergement)
    {
        $this->load->database();       

        $this->db->select( "*" );
        $this->db->from( 't_ip' );
        $this->db->like( 'id_heberg', $id_hebergement );
        $this->db->order_by('id_heberg', 'asc');
        $query = $this->db->get();
        $ip_data = $query->result();
      
        return $ip_data;
    }

     /*
     * Get t_ip by id_hebergement
     */
    function get_ip_id_hebergement($id_hebergement)
    {
        return $this->db->get_where('t_ip',array('id_heberg'=>$id_hebergement))->result_array();
    }
}

