<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Registrar_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get t_registrar by id
     */
    function get_t_registrar($id)
    {
        return $this->db->get_where('t_registrar',array('id'=>$id))->row_array();
    }

    function get_t_registrar_by_name($name)
    {
        return $this->db->get_where('t_registrar',array('name'=>$name))->row_array();
    }
        
    /*
     * Get all t_registrar
     */
    function get_all_t_registrar()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('t_registrar')->result_array();
    }
        
    /*
     * function to add new t_registrar
     */
    function add_t_registrar($params)
    {
        $this->db->insert('t_registrar',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update t_registrar
     */
    function update_t_registrar($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('t_registrar',$params);
    }
    
    /*
     * function to delete t_registrar
     */
    function delete_t_registrar($id)
    {
        return $this->db->delete('t_registrar',array('id'=>$id));
    }
}
