<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Theme_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get t_theme by id
     */
    function get_t_theme($id)
    {
        return $this->db->get_where('t_theme',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all t_theme
     */
    function get_all_t_theme()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('t_theme')->result_array();
    }
        
    /*
     * function to add new t_theme
     */
    function add_t_theme($params)
    {
        $this->db->insert('t_theme',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update t_theme
     */
    function update_t_theme($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('t_theme',$params);
    }
    
    /*
     * function to delete t_theme
     */
    function delete_t_theme($id)
    {
        return $this->db->delete('t_theme',array('id'=>$id));
    }
}
