<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Theme_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get t_theme by id
     */
    function get_t_theme($id)
    {
        return $this->db->get_where('t_theme',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all t_theme
     */
    function get_all_t_theme()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('t_theme')->result_array();
    }
        
    /*
     * function to add new t_theme
     */
    function add_t_theme($params)
    {
        $this->db->insert('t_theme',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update t_theme
     */
    function update_t_theme($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('t_theme',$params);
    }
    
    /*
     * function to delete t_theme
     */
    function delete_t_theme($id)
    {
        return $this->db->delete('t_theme',array('id'=>$id));
    }

     /*
     * Get t_theme by term
     */
    function suggested_theme($term)
    {
            $this->load->database();
         
            $this->db->select( "*" );
            $this->db->from( 't_theme' );
            $this->db->like( 'name', $term );
            $this->db->order_by('name', 'asc');
            $query = $this->db->get();
            $theme_data = $query->result();
           
            $themes = array();
            foreach($theme_data as $key):
              
                $a = array(
                    'id' => trim($key->id),
                    'label' => trim($key->name),
                    'value' => trim($key->name)
                );

                $themes[] = $a;
            endforeach;
          
            echo json_encode($themes);
            die;
    }

    /*
     * Get t_theme by name
     */
    function get_t_theme_by_name($name)
    {
        return $this->db->get_where('t_theme',array('name'=>$name))->row_array();
    }
}
